# Generated by Django 3.1.1 on 2020-10-22 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connect',
            old_name='message',
            new_name='desc',
        ),
    ]
