# Generated by Django 3.0.10 on 2020-10-22 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_auto_20201022_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connect',
            name='date',
        ),
    ]
