# Generated by Django 3.0.10 on 2020-10-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0005_auto_20201023_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='date',
            field=models.DateField(default='0001-01-01'),
        ),
    ]
