# Generated by Django 3.0.10 on 2020-10-22 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0006_auto_20201023_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connect',
            name='date',
        ),
    ]
