# Generated by Django 3.0.10 on 2020-10-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0007_remove_connect_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
