# Generated by Django 3.0.10 on 2020-10-20 17:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201020_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 20, 17, 52, 24, 172561, tzinfo=utc)),
        ),
    ]
