# Generated by Django 3.0.10 on 2020-10-21 17:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201020_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 17, 58, 40, 746537, tzinfo=utc)),
        ),
    ]
